version: "3.1"
secrets:
  maps-api-key:
    file: ./secrets/maps-api-key
  tls-key:
      file: ./secrets/tls/dev/self-signed.key
  tls-cert:
      file: ./secrets/tls/dev/self-signed.crt
  tls-dhparam:
      file: ./secrets/tls/dev/dhparam.pem
  aws-administrator-credentials:
    file: ./secrets/aws-administrator-credentials
services:
  app:
    image: nginx
    container_name: app-proxy
    depends_on:
      - app-core
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app
    secrets:
      - tls-key
      - tls-cert
      - tls-dhparam
    ports:
      - "443:443"
  app-core:
    image: lukeparzych/datenight:latest
    container_name: app-core
    command: [yarn, start]
    working_dir: /usr/src/app
    networks:
      - app
    volumes:
        - .:/usr/src/app
    secrets:
      - aws-administrator-credentials
    environment:
      PORT: 80
      NODE_ENV: development
  tf:
    image: hashicorp/terraform
    container_name: tf
    working_dir: /tf
    volumes:
      - ./terraform:/tf
    secrets:
      - aws-administrator-credentials
      - maps-api-key
networks:
  app:

